const teacher_data = [
  {
    fullName: "Rajesh Kumar",
    email: "rajesh.kumar@example.com",
    username: "rajesh123",
    password: "R@j3sh#2020",
    phoneNumber: "9876543210",
    gender: "Male",
    department: "Mathematics",
    designation: "Assistant Professor",
    joiningDate: new Date("2020-01-15"),
    role: "Teacher",
  },
  {
    fullName: "Anita Sharma",
    email: "anita.sharma@example.com",
    username: "anita123",
    password: "An!t@2021",
    phoneNumber: "9876543211",
    gender: "Female",
    department: "Computer Science",
    designation: "Professor",
    joiningDate: new Date("2019-07-10"),
    role: "Teacher",
  },
  {
    fullName: "Sunita Verma",
    email: "sunita.verma@example.com",
    username: "sunita123",
    password: "Sun!t@2022",
    phoneNumber: "9876543212",
    gender: "Female",
    department: "Physics",
    designation: "Assistant Professor",
    joiningDate: new Date("2021-03-20"),
    role: "Teacher",
  },
  {
    fullName: "Amit Singh",
    email: "amit.singh@example.com",
    username: "amit123",
    password: "Am!t#2023",
    phoneNumber: "9876543213",
    gender: "Male",
    department: "Chemistry",
    designation: "Lecturer",
    joiningDate: new Date("2018-08-05"),
    role: "Teacher",
  },
  {
    fullName: "Priya Patel",
    email: "priya.patel@example.com",
    username: "priya123",
    password: "Pr!y@2024",
    phoneNumber: "9876543214",
    gender: "Female",
    department: "English",
    designation: "Lecturer",
    joiningDate: new Date("2022-01-10"),
    role: "Teacher",
  },
];

export const data1 = teacher_data;

const adminData = [
  {
    adminId: "A001",
    name: "Sunil Verma",
    username: "adminsunil",
    password: "sunil123",
  },
  {
    adminId: "A002",
    name: "Priya Sharma",
    username: "adminpriya",
    password: "priya123",
  },
];

export const data2 = adminData;

const studentData = [
  {
    name: "Ravi Kumar",
    class: "10A",
    department: "Science",
    phoneNumber: "9876543210",
    fatherName: "Mahesh Kumar",
    address: "Village Rampur, UP",
  },
  {
    name: "Sunita Sharma",
    class: "9B",
    department: "Mathematics",
    phoneNumber: "9876543211",
    fatherName: "Rajesh Sharma",
    address: "Village Bhagalpur, Bihar",
  },
  {
    name: "Amit Yadav",
    class: "8A",
    department: "English",
    phoneNumber: "9876543212",
    fatherName: "Dinesh Yadav",
    address: "Village Sitapur, UP",
  },
  {
    name: "Priya Verma",
    class: "10B",
    department: "Science",
    phoneNumber: "9876543213",
    fatherName: "Arun Verma",
    address: "Village Rohtak, Haryana",
  },
  {
    name: "Suresh Singh",
    class: "9A",
    department: "Mathematics",
    phoneNumber: "9876543214",
    fatherName: "Vinod Singh",
    address: "Village Varanasi, UP",
  },
  {
    name: "Anita Gupta",
    class: "8B",
    department: "English",
    phoneNumber: "9876543215",
    fatherName: "Mukesh Gupta",
    address: "Village Gaya, Bihar",
  },
  {
    name: "Rahul Mehta",
    class: "10C",
    department: "Science",
    phoneNumber: "9876543216",
    fatherName: "Sanjay Mehta",
    address: "Village Ambala, Haryana",
  },
  {
    name: "Neha Patel",
    class: "9C",
    department: "Mathematics",
    phoneNumber: "9876543217",
    fatherName: "Rakesh Patel",
    address: "Village Anand, Gujarat",
  },
  {
    name: "Vikas Chauhan",
    class: "8C",
    department: "English",
    phoneNumber: "9876543218",
    fatherName: "Om Prakash Chauhan",
    address: "Village Meerut, UP",
  },
  {
    name: "Pooja Rani",
    class: "10D",
    department: "Science",
    phoneNumber: "9876543219",
    fatherName: "Shyam Lal",
    address: "Village Karnal, Haryana",
  },
];

export const data3 = studentData;
